export const mock = {
  id: 24,
  playlist: 'PLu0SKb668nMemkZ7wQWhtbBauKbNJ9cD-',
  weekId: 257,
  programStatisticId: 11,
  week: { id: 257, number: 6, programId: 58 },
  sessionStatistics: [
    {
      id: 60,
      sessionId: 922,
      weekStatisticId: 24,
      session: { id: 922, name: 'day 1', order: 1, weekId: 257 },
      sessionItemStatistics: [
        {
          id: 144,
          rpe: 8,
          notes: '',
          sessionItemId: 1582,
          sessionStatisticId: 60,
          sessionItem: {
            id: 1582,
            reps: 2,
            AMRAP: false,
            leftRight: false,
            sets: 5,
            weight: 0,
            weightUnit: 'lbs',
            intensity: 'bodyweight',
            tempo: 'self directed',
            order: 1,
            exerciseId: 32,
            sessionId: 922,
            exercise: {
              id: 32,
              name: 'HSPU',
              push: true,
              pull: false,
              intensities: ['bodyweight'],
              leftRight: false,
            },
          },
          setStatistics: [
            {
              id: 475,
              set: 1,
              reps: 0,
              weight: 0,
              sessionItemStatisticId: 144,
            },
            {
              id: 476,
              set: 2,
              reps: 0,
              weight: 0,
              sessionItemStatisticId: 144,
            },
            {
              id: 477,
              set: 3,
              reps: 0,
              weight: 0,
              sessionItemStatisticId: 144,
            },
            {
              id: 478,
              set: 4,
              reps: 0,
              weight: 0,
              sessionItemStatisticId: 144,
            },
            {
              id: 479,
              set: 5,
              reps: 0,
              weight: 0,
              sessionItemStatisticId: 144,
            },
          ],
        },
        {
          id: 145,
          rpe: 8,
          notes: '',
          sessionItemId: 1583,
          sessionStatisticId: 60,
          sessionItem: {
            id: 1583,
            reps: 0,
            AMRAP: true,
            leftRight: false,
            sets: 4,
            weight: 0,
            weightUnit: 'lbs',
            intensity: 'Single Leg',
            tempo: '-',
            order: 2,
            exerciseId: 7,
            sessionId: 922,
            exercise: {
              id: 7,
              name: 'Isometric Planche Holds',
              push: true,
              pull: false,
              intensities: [
                'Tuck',
                'Straddle to tuck',
                'Single Leg',
                'Straddle',
              ],
              leftRight: false,
            },
          },
          setStatistics: [
            {
              id: 480,
              set: 1,
              reps: 6,
              weight: 0,
              sessionItemStatisticId: 145,
            },
            {
              id: 481,
              set: 2,
              reps: 4,
              weight: 0,
              sessionItemStatisticId: 145,
            },
            {
              id: 482,
              set: 3,
              reps: 4,
              weight: 0,
              sessionItemStatisticId: 145,
            },
            {
              id: 483,
              set: 4,
              reps: 4,
              weight: 0,
              sessionItemStatisticId: 145,
            },
          ],
        },
        {
          id: 146,
          rpe: 8,
          notes: '',
          sessionItemId: 1584,
          sessionStatisticId: 60,
          sessionItem: {
            id: 1584,
            reps: 1,
            AMRAP: false,
            leftRight: false,
            sets: 4,
            weight: 0,
            weightUnit: 'lbs',
            intensity: 'tuck to straddle',
            tempo: '5 second hold in bent arm planche',
            order: 3,
            exerciseId: 33,
            sessionId: 922,
            exercise: {
              id: 33,
              name: 'MAPPU to bent arm planche',
              push: true,
              pull: false,
              intensities: ['tuck to straddle'],
              leftRight: false,
            },
          },
          setStatistics: [
            {
              id: 484,
              set: 1,
              reps: 0,
              weight: 0,
              sessionItemStatisticId: 146,
            },
            {
              id: 485,
              set: 2,
              reps: 0,
              weight: 0,
              sessionItemStatisticId: 146,
            },
            {
              id: 486,
              set: 3,
              reps: 0,
              weight: 0,
              sessionItemStatisticId: 146,
            },
            {
              id: 487,
              set: 4,
              reps: 0,
              weight: 0,
              sessionItemStatisticId: 146,
            },
          ],
        },
        {
          id: 147,
          rpe: 8,
          notes: '',
          sessionItemId: 1585,
          sessionStatisticId: 60,
          sessionItem: {
            id: 1585,
            reps: 8,
            AMRAP: false,
            leftRight: false,
            sets: 3,
            weight: 0,
            weightUnit: 'lbs',
            intensity: 'Straddle / full, with band',
            tempo: '2 second pause at bottom',
            order: 4,
            exerciseId: 23,
            sessionId: 922,
            exercise: {
              id: 23,
              name: 'Planche Push-Ups',
              push: true,
              pull: false,
              intensities: [
                'Tuck on Paralletes',
                'Straddle / full, with band',
                'Straddle to Tuck',
              ],
              leftRight: false,
            },
          },
          setStatistics: [
            {
              id: 488,
              set: 1,
              reps: 0,
              weight: 0,
              sessionItemStatisticId: 147,
            },
            {
              id: 489,
              set: 2,
              reps: 0,
              weight: 0,
              sessionItemStatisticId: 147,
            },
            {
              id: 490,
              set: 3,
              reps: 0,
              weight: 0,
              sessionItemStatisticId: 147,
            },
          ],
        },
        {
          id: 148,
          rpe: 8,
          notes: '',
          sessionItemId: 1586,
          sessionStatisticId: 60,
          sessionItem: {
            id: 1586,
            reps: 5,
            AMRAP: false,
            leftRight: false,
            sets: 3,
            weight: 0,
            weightUnit: 'lbs',
            intensity: 'feet raise at bottom',
            tempo: '2 second float at bottom',
            order: 5,
            exerciseId: 17,
            sessionId: 922,
            exercise: {
              id: 17,
              name: 'Pike push-ups',
              push: true,
              pull: false,
              intensities: ['Self directed', 'feet raise at bottom'],
              leftRight: false,
            },
          },
          setStatistics: [
            {
              id: 491,
              set: 1,
              reps: 0,
              weight: 0,
              sessionItemStatisticId: 148,
            },
            {
              id: 492,
              set: 2,
              reps: 0,
              weight: 0,
              sessionItemStatisticId: 148,
            },
            {
              id: 493,
              set: 3,
              reps: 0,
              weight: 0,
              sessionItemStatisticId: 148,
            },
          ],
        },
      ],
    },
    {
      id: 61,
      sessionId: 923,
      weekStatisticId: 24,
      session: { id: 923, name: 'day 2', order: 2, weekId: 257 },
      sessionItemStatistics: [
        {
          id: 29,
          rpe: 8,
          notes: '',
          sessionItemId: 1590,
          sessionStatisticId: 61,
          sessionItem: {
            id: 1590,
            reps: 0,
            AMRAP: true,
            leftRight: false,
            sets: 3,
            weight: 0,
            weightUnit: 'lbs',
            intensity: 'bodyweight',
            tempo: 'self directed',
            order: 4,
            exerciseId: 36,
            sessionId: 923,
            exercise: {
              id: 36,
              name: 'Pull Ups',
              push: false,
              pull: true,
              intensities: ['bodyweight', 'weighted'],
              leftRight: false,
            },
          },
          setStatistics: [
            { id: 503, set: 1, reps: 3, weight: 0, sessionItemStatisticId: 29 },
            { id: 504, set: 2, reps: 4, weight: 0, sessionItemStatisticId: 29 },
            { id: 505, set: 3, reps: 4, weight: 0, sessionItemStatisticId: 29 },
          ],
        },
        {
          id: 30,
          rpe: 8,
          notes: '',
          sessionItemId: 1589,
          sessionStatisticId: 61,
          sessionItem: {
            id: 1589,
            reps: 0,
            AMRAP: true,
            leftRight: false,
            sets: 4,
            weight: 35,
            weightUnit: 'lbs',
            intensity: 'weighted',
            tempo: 'self directed',
            order: 3,
            exerciseId: 10,
            sessionId: 923,
            exercise: {
              id: 10,
              name: 'Chin-ups',
              push: false,
              pull: true,
              intensities: ['bodyweight', 'weighted'],
              leftRight: false,
            },
          },
          setStatistics: [
            { id: 103, set: 1, reps: 9, weight: 0, sessionItemStatisticId: 30 },
            { id: 104, set: 2, reps: 7, weight: 0, sessionItemStatisticId: 30 },
            { id: 105, set: 3, reps: 6, weight: 0, sessionItemStatisticId: 30 },
            { id: 106, set: 4, reps: 5, weight: 0, sessionItemStatisticId: 30 },
          ],
        },
        {
          id: 31,
          rpe: 8,
          notes: '',
          sessionItemId: 1588,
          sessionStatisticId: 61,
          sessionItem: {
            id: 1588,
            reps: 5,
            AMRAP: false,
            leftRight: false,
            sets: 4,
            weight: 0,
            weightUnit: 'lbs',
            intensity: 'Advanced Single Leg',
            tempo: '2 second hold in lever',
            order: 2,
            exerciseId: 35,
            sessionId: 923,
            exercise: {
              id: 35,
              name: 'L-Sit to front lever',
              push: false,
              pull: true,
              intensities: ['Advanced Single Leg'],
              leftRight: false,
            },
          },
          setStatistics: [
            { id: 499, set: 1, reps: 0, weight: 0, sessionItemStatisticId: 31 },
            { id: 500, set: 2, reps: 0, weight: 0, sessionItemStatisticId: 31 },
            { id: 501, set: 3, reps: 0, weight: 0, sessionItemStatisticId: 31 },
            { id: 502, set: 4, reps: 0, weight: 0, sessionItemStatisticId: 31 },
          ],
        },
        {
          id: 32,
          rpe: 8,
          notes: '',
          sessionItemId: 1587,
          sessionStatisticId: 61,
          sessionItem: {
            id: 1587,
            reps: 6,
            AMRAP: false,
            leftRight: false,
            sets: 5,
            weight: 0,
            weightUnit: 'lbs',
            intensity: 'band assisted',
            tempo: 'self directed',
            order: 1,
            exerciseId: 37,
            sessionId: 923,
            exercise: {
              id: 37,
              name: 'Front Lever Pull Ups',
              push: false,
              pull: true,
              intensities: ['band assisted', 'advanced tuck'],
              leftRight: false,
            },
          },
          setStatistics: [
            { id: 494, set: 1, reps: 0, weight: 0, sessionItemStatisticId: 32 },
            { id: 495, set: 2, reps: 0, weight: 0, sessionItemStatisticId: 32 },
            { id: 496, set: 3, reps: 0, weight: 0, sessionItemStatisticId: 32 },
            { id: 497, set: 4, reps: 0, weight: 0, sessionItemStatisticId: 32 },
            { id: 498, set: 5, reps: 0, weight: 0, sessionItemStatisticId: 32 },
          ],
        },
      ],
    },
    {
      id: 62,
      sessionId: 924,
      weekStatisticId: 24,
      session: { id: 924, name: 'day 3', order: 3, weekId: 257 },
      sessionItemStatistics: [
        {
          id: 149,
          rpe: 8,
          notes: '',
          sessionItemId: 1591,
          sessionStatisticId: 62,
          sessionItem: {
            id: 1591,
            reps: 1,
            AMRAP: false,
            leftRight: false,
            sets: 5,
            weight: 0,
            weightUnit: 'lbs',
            intensity: 'straddle',
            tempo: '5 second hold at the bottom',
            order: 1,
            exerciseId: 5,
            sessionId: 924,
            exercise: {
              id: 5,
              name: '90 Degree Negatives',
              push: true,
              pull: false,
              intensities: ['straddle', 'full'],
              leftRight: false,
            },
          },
          setStatistics: [
            {
              id: 506,
              set: 1,
              reps: 0,
              weight: 0,
              sessionItemStatisticId: 149,
            },
            {
              id: 507,
              set: 2,
              reps: 0,
              weight: 0,
              sessionItemStatisticId: 149,
            },
            {
              id: 508,
              set: 3,
              reps: 0,
              weight: 0,
              sessionItemStatisticId: 149,
            },
            {
              id: 509,
              set: 4,
              reps: 0,
              weight: 0,
              sessionItemStatisticId: 149,
            },
            {
              id: 510,
              set: 5,
              reps: 0,
              weight: 0,
              sessionItemStatisticId: 149,
            },
          ],
        },
        {
          id: 150,
          rpe: 8,
          notes: '',
          sessionItemId: 1593,
          sessionStatisticId: 62,
          sessionItem: {
            id: 1593,
            reps: 5,
            AMRAP: false,
            leftRight: false,
            sets: 3,
            weight: 0,
            weightUnit: 'lbs',
            intensity: 'feet raise at bottom',
            tempo: '2 second float at bottom',
            order: 2,
            exerciseId: 17,
            sessionId: 924,
            exercise: {
              id: 17,
              name: 'Pike push-ups',
              push: true,
              pull: false,
              intensities: ['Self directed', 'feet raise at bottom'],
              leftRight: false,
            },
          },
          setStatistics: [
            {
              id: 511,
              set: 1,
              reps: 0,
              weight: 0,
              sessionItemStatisticId: 150,
            },
            {
              id: 512,
              set: 2,
              reps: 0,
              weight: 0,
              sessionItemStatisticId: 150,
            },
            {
              id: 513,
              set: 3,
              reps: 0,
              weight: 0,
              sessionItemStatisticId: 150,
            },
          ],
        },
        {
          id: 151,
          rpe: 8,
          notes: '',
          sessionItemId: 1592,
          sessionStatisticId: 62,
          sessionItem: {
            id: 1592,
            reps: 0,
            AMRAP: true,
            leftRight: false,
            sets: 4,
            weight: 0,
            weightUnit: 'lbs',
            intensity: 'Single Leg',
            tempo: '-',
            order: 3,
            exerciseId: 7,
            sessionId: 924,
            exercise: {
              id: 7,
              name: 'Isometric Planche Holds',
              push: true,
              pull: false,
              intensities: [
                'Tuck',
                'Straddle to tuck',
                'Single Leg',
                'Straddle',
              ],
              leftRight: false,
            },
          },
          setStatistics: [
            {
              id: 514,
              set: 1,
              reps: 5,
              weight: 0,
              sessionItemStatisticId: 151,
            },
            {
              id: 515,
              set: 2,
              reps: 5,
              weight: 0,
              sessionItemStatisticId: 151,
            },
            {
              id: 516,
              set: 3,
              reps: 2,
              weight: 0,
              sessionItemStatisticId: 151,
            },
            {
              id: 517,
              set: 4,
              reps: 0,
              weight: 0,
              sessionItemStatisticId: 151,
            },
          ],
        },
        {
          id: 152,
          rpe: 8,
          notes: '',
          sessionItemId: 1594,
          sessionStatisticId: 62,
          sessionItem: {
            id: 1594,
            reps: 1,
            AMRAP: false,
            leftRight: false,
            sets: 4,
            weight: 0,
            weightUnit: 'lbs',
            intensity: 'tuck to straddle',
            tempo: '5 second hold in bent arm planche',
            order: 4,
            exerciseId: 33,
            sessionId: 924,
            exercise: {
              id: 33,
              name: 'MAPPU to bent arm planche',
              push: true,
              pull: false,
              intensities: ['tuck to straddle'],
              leftRight: false,
            },
          },
          setStatistics: [
            {
              id: 518,
              set: 1,
              reps: 0,
              weight: 0,
              sessionItemStatisticId: 152,
            },
            {
              id: 519,
              set: 2,
              reps: 0,
              weight: 0,
              sessionItemStatisticId: 152,
            },
            {
              id: 520,
              set: 3,
              reps: 0,
              weight: 0,
              sessionItemStatisticId: 152,
            },
            {
              id: 521,
              set: 4,
              reps: 0,
              weight: 0,
              sessionItemStatisticId: 152,
            },
          ],
        },
        {
          id: 153,
          rpe: 8,
          notes: '',
          sessionItemId: 1595,
          sessionStatisticId: 62,
          sessionItem: {
            id: 1595,
            reps: 8,
            AMRAP: false,
            leftRight: false,
            sets: 3,
            weight: 0,
            weightUnit: 'lbs',
            intensity: 'Straddle / full, with band',
            tempo: '2 second pause at bottom',
            order: 5,
            exerciseId: 23,
            sessionId: 924,
            exercise: {
              id: 23,
              name: 'Planche Push-Ups',
              push: true,
              pull: false,
              intensities: [
                'Tuck on Paralletes',
                'Straddle / full, with band',
                'Straddle to Tuck',
              ],
              leftRight: false,
            },
          },
          setStatistics: [
            {
              id: 522,
              set: 1,
              reps: 0,
              weight: 0,
              sessionItemStatisticId: 153,
            },
            {
              id: 523,
              set: 2,
              reps: 0,
              weight: 0,
              sessionItemStatisticId: 153,
            },
            {
              id: 524,
              set: 3,
              reps: 0,
              weight: 0,
              sessionItemStatisticId: 153,
            },
          ],
        },
      ],
    },
    {
      id: 63,
      sessionId: 925,
      weekStatisticId: 24,
      session: { id: 925, name: 'day 4', order: 4, weekId: 257 },
      sessionItemStatistics: [
        {
          id: 33,
          rpe: 8,
          notes: '',
          sessionItemId: 1600,
          sessionStatisticId: 63,
          sessionItem: {
            id: 1600,
            reps: 0,
            AMRAP: true,
            leftRight: false,
            sets: 2,
            weight: 0,
            weightUnit: 'lbs',
            intensity: 'Tuck',
            tempo: '-',
            order: 5,
            exerciseId: 9,
            sessionId: 925,
            exercise: {
              id: 9,
              name: 'Isometric Front Lever',
              push: false,
              pull: true,
              intensities: [
                'Self directed',
                'Single leg to tuck',
                'Tuck',
                'Single Leg',
                'with band',
                'Advanced Single Leg',
              ],
              leftRight: false,
            },
          },
          setStatistics: [
            { id: 540, set: 1, reps: 0, weight: 0, sessionItemStatisticId: 33 },
            { id: 541, set: 2, reps: 0, weight: 0, sessionItemStatisticId: 33 },
          ],
        },
        {
          id: 34,
          rpe: 8,
          notes: '',
          sessionItemId: 1599,
          sessionStatisticId: 63,
          sessionItem: {
            id: 1599,
            reps: 0,
            AMRAP: true,
            leftRight: false,
            sets: 3,
            weight: 0,
            weightUnit: 'lbs',
            intensity: 'bodyweight',
            tempo: 'self directed',
            order: 4,
            exerciseId: 36,
            sessionId: 925,
            exercise: {
              id: 36,
              name: 'Pull Ups',
              push: false,
              pull: true,
              intensities: ['bodyweight', 'weighted'],
              leftRight: false,
            },
          },
          setStatistics: [
            { id: 537, set: 1, reps: 5, weight: 0, sessionItemStatisticId: 34 },
            { id: 538, set: 2, reps: 4, weight: 0, sessionItemStatisticId: 34 },
            { id: 539, set: 3, reps: 6, weight: 0, sessionItemStatisticId: 34 },
          ],
        },
        {
          id: 35,
          rpe: 8,
          notes: '',
          sessionItemId: 1598,
          sessionStatisticId: 63,
          sessionItem: {
            id: 1598,
            reps: 0,
            AMRAP: true,
            leftRight: true,
            sets: 3,
            weight: 0,
            weightUnit: 'lbs',
            intensity: '2-finger assisted, bodyweight',
            tempo: 'self directed',
            order: 3,
            exerciseId: 34,
            sessionId: 925,
            exercise: {
              id: 34,
              name: 'OAC',
              push: false,
              pull: true,
              intensities: ['2-finger assisted, bodyweight'],
              leftRight: true,
            },
          },
          setStatistics: [
            { id: 534, set: 1, reps: 0, weight: 0, sessionItemStatisticId: 35 },
            { id: 535, set: 2, reps: 0, weight: 0, sessionItemStatisticId: 35 },
            { id: 536, set: 3, reps: 0, weight: 0, sessionItemStatisticId: 35 },
          ],
        },
        {
          id: 36,
          rpe: 8,
          notes: '',
          sessionItemId: 1597,
          sessionStatisticId: 63,
          sessionItem: {
            id: 1597,
            reps: 5,
            AMRAP: false,
            leftRight: false,
            sets: 4,
            weight: 0,
            weightUnit: 'lbs',
            intensity: 'Advanced Single Leg',
            tempo: '2 second hold in lever',
            order: 2,
            exerciseId: 35,
            sessionId: 925,
            exercise: {
              id: 35,
              name: 'L-Sit to front lever',
              push: false,
              pull: true,
              intensities: ['Advanced Single Leg'],
              leftRight: false,
            },
          },
          setStatistics: [
            { id: 530, set: 1, reps: 0, weight: 0, sessionItemStatisticId: 36 },
            { id: 531, set: 2, reps: 0, weight: 0, sessionItemStatisticId: 36 },
            { id: 532, set: 3, reps: 0, weight: 0, sessionItemStatisticId: 36 },
            { id: 533, set: 4, reps: 0, weight: 0, sessionItemStatisticId: 36 },
          ],
        },
        {
          id: 154,
          rpe: 8,
          notes: '',
          sessionItemId: 1596,
          sessionStatisticId: 63,
          sessionItem: {
            id: 1596,
            reps: 6,
            AMRAP: false,
            leftRight: false,
            sets: 5,
            weight: 0,
            weightUnit: 'lbs',
            intensity: 'band assisted',
            tempo: 'self directed',
            order: 1,
            exerciseId: 37,
            sessionId: 925,
            exercise: {
              id: 37,
              name: 'Front Lever Pull Ups',
              push: false,
              pull: true,
              intensities: ['band assisted', 'advanced tuck'],
              leftRight: false,
            },
          },
          setStatistics: [
            {
              id: 525,
              set: 1,
              reps: 0,
              weight: 0,
              sessionItemStatisticId: 154,
            },
            {
              id: 526,
              set: 2,
              reps: 0,
              weight: 0,
              sessionItemStatisticId: 154,
            },
            {
              id: 527,
              set: 3,
              reps: 0,
              weight: 0,
              sessionItemStatisticId: 154,
            },
            {
              id: 528,
              set: 4,
              reps: 0,
              weight: 0,
              sessionItemStatisticId: 154,
            },
            {
              id: 529,
              set: 5,
              reps: 0,
              weight: 0,
              sessionItemStatisticId: 154,
            },
          ],
        },
      ],
    },
  ],
};
